DGP-002 Arreglar el header
Jesusdavid20/Chef-Profile-Jesus-Acosta pull request #7
Opened 2022-08-05 02:25 UTC by Jesusdavid20

Hi, good night Mr Jorge

In this branch i worked in the header, specifically in the position of the things in version mobile and desktop

i waiting for comments

kisses

2022-08-05 02:27 UTC, Jesusdavid20 commented
Please excuse me for not putting the correct name to the branch on github

2022-08-05 09:02 UTC, JorgEdmundo requested changes
Jesus, there is a great improvement in the header. I liked the colors that you picked and the new distribution. I also liked what you did with the logo. Very well done.
There are some html structuring that we could discuss in detail and some css improvements. Nothing big, we are close to the final part.
Nice Job, I liked this PR and how you are improve. Keep it up!

2022-08-05 09:02 UTC, JorgEdmundo commented on index.html
> +    <header >
No space after the header word.
```suggestion
    <header> 
```

2022-08-05 09:02 UTC, JorgEdmundo commented on index.html
> +    <div class="mobileSearchBar">
Suggestion: move the search bar inside the mobile menu, the one that closes and expands.

2022-08-05 09:02 UTC, JorgEdmundo commented on styles/styles.css
> +  flex-direction: row;
`flex-direction: row;` is set by default. This property is redundant. If you change it with a media query, then it would make sense.

2022-08-05 09:02 UTC, JorgEdmundo commented on styles/styles.css
> +    flex-direction: row;
`flex-direction: row;` is set by default.

2022-08-05 09:02 UTC, JorgEdmundo commented on styles/styles.scss
> +    flex-direction: row;
`flex-direction: row;` is set by default.

2022-08-05 09:02 UTC, JorgEdmundo commented on styles/styles.scss
> +        flex-direction: row;
`flex-direction: row;` is set by default.

2022-08-05 09:02 UTC, JorgEdmundo commented on styles/styles.scss
> +        flex-direction: row;
`flex-direction: row;` is set by default.

2022-08-06 02:42 UTC, Jesusdavid20 commented
Jorge, I can no put the search bar into the mobileMenu, the search bar styles that are copied won't let me, there is something I don't see

2022-08-06 02:43 UTC, Jesusdavid20 commented
help :(

2022-08-06 02:48 UTC, Jesusdavid20 commented
when you are agreed with the changes for the header I have to aplicate this changes in all pages before merge

2022-08-12 03:53 UTC, Jesusdavid20 commented
Hi Jorge, Good night (for you good morning)

Here I leave you the branch "header" with changes like:

1.- finally I put on the header the search bar

2.- I changed the color pallets in the page because I couldn't keep seeing that fuking brown

3.- The footer have a new distribution, colors and some things

I whaiting for comments

Danke vielmals

kisses

2022-08-12 07:56 UTC, JorgEdmundo approved these changes
Jesus, the changes and improvements are outstanding! Well job and very well done. I checked the page and the responsiveness and it looks excellent. The color palette is beautiful. I also liked what you did with the footer. It is still a long way but you are on the right track. Keep up the good work.

2022-08-12 07:56 UTC, JorgEdmundo commented on index.html
> +        <div class="mobileHeader">
Check this:
![Screenshot 2022-08-05 at 10 50 14](https://user-images.githubusercontent.com/3438819/183043131-c0384402-6424-48ef-94d9-c7641a7f7780.png)

2022-08-12 07:56 UTC, JorgEdmundo commented on styles/styles.scss
>      display: inline-block;
Remove this property: `display: inline-block;` since you are using display flex.

2022-08-12 07:56 UTC, JorgEdmundo commented on styles/styles.scss
> +    max-width: 420px;
the magic number ;)

2022-08-16 07:11 UTC, JorgEdmundo approved these changes

2022-08-18 00:51 UTC, merged